--3.TERCER TRIGGER
-- No permite ingresar en el campo CANTIDAD de la tabla DETALLE_PEDIDO una cantidad menor o igual a cero. 

create or replace TRIGGER TR_B_IU_CANTIDAD_DETALLEPEDIDO
BEFORE 
INSERT OR UPDATE OF CANTIDAD ON DETALLE_PEDIDO
FOR EACH ROW WHEN (NEW.CANTIDAD <=0)
DECLARE
BEGIN
    RAISE_APPLICATION_ERROR(-20039, 'INGRESO DE CANTIDAD NO ES LA CORRECTA: '|| :NEW.CANTIDAD);
END TR_B_IU_CANTIDAD_DETALLEPEDIDO;



----OPERACION QUE DESPIERTA EL TRIGGER

 INSERT INTO DETALLE_PEDIDO (ID_PRODUCTO,ID_PEDIDO,CANTIDAD,PRECIO_SUBTOTAL,DESCUENTO,PRECIO_TOTAL)
 VALUES (1,1,0,12,8,4);
  