
--3.TERCER TRIGGER
--El campo FORMA_ENVIO de la tabla PEDIDO solo puede tener los valores “SERVIENTREGA” Y “WESTERUNION”

create or replace TRIGGER TR_B_IU_FORMAENVIO_PEDIDO 
BEFORE 
INSERT OR UPDATE OF FORMA_ENVIO ON PEDIDO
FOR EACH ROW WHEN (NEW.FORMA_ENVIO<>'SERVIENTREGA' AND NEW.FORMA_ENVIO<>'WESTERUNION')
DECLARE
BEGIN
    RAISE_APPLICATION_ERROR(-20039, 'LA OPCION DE ENVIO NO ES LA CORRECTA, PUEDE SER POR SERVIENTREGA O WESTERUNION no: '|| :new.FORMA_ENVIO);
END TR_B_IU_FORMAENVIO_PEDIDO ;

----OPERACION QUE DESPIERTA EL TRIGGER


INSERT INTO PEDIDO (ID_PEDIDO,ID_VENDEDOR,ID_CLIENTE,FECHA_REALIZACION,FECHA_ENVIO,FORMA_ENVIO)
VALUES (1,1,1,'3/09/2016','3/10/2016','SERVI');