
--8. OCTAVO TRIGGER
--El campo CARGO_PROVEEDOR de la tabla PROVEEDOR solo puede tener los valores “GERENTE” Y “EMPLEADO”. 

create or replace TRIGGER TR_B_IU_CARGOPROVEEDOR 
BEFORE 
INSERT OR UPDATE OF CARGO_CONTACTO ON PROVEEDOR
FOR EACH ROW WHEN (NEW.CARGO_CONTACTO<>'GERENTE' AND NEW.CARGO_CONTACTO<>'EMPLEADO')
DECLARE
BEGIN
    RAISE_APPLICATION_ERROR(-20039, 'EL CARGO PUEDE SER GERENTE O EMPLEADO, NO:'|| :NEW.CARGO_CONTACTO);
END TR_B_IU_CARGOPROVEEDOR;


----OPERACION QUE DESPIERTA EL TRIGGER
INSERT INTO PROVEEDOR (ID_PROVEEDOR,NOMBRE_EMPRESA,PAIS_EMPRESA,CIUDAD_EMPRESA,DIRECCION_EMPRESA,NOMBRE_CONTACTO,APELLIDO_CONTACTO,TELEFONO_CONTACTO,CARGO_CONTACTO)
VALUES (1,'LA FABRIL S.A','ECUADOR','MANTA','FABRIL','JUAN ANDRES','MORALES ZAMBRANO','0998769490','PROVEE');