
--9.NOVENO TRIGGER
-- Limita el sueldo del vendedor que no debe sobrepasar a los 375 dólares. 

create or replace TRIGGER TR_B_IU_SUELDOVENDEDOR

BEFORE INSERT OR UPDATE OF SUELDO_VENDEDOR ON VENDEDOR 
FOR EACH ROW
BEGIN
  IF :NEW.SUELDO_VENDEDOR > 375 
  THEN 
  RAISE_APPLICATION_ERROR(-20039, 'EL SUELDO SOBREPASA EL SUELDO BASICO $375 DISPUESTO POR LA CONSTITUCION: '|| :NEW.SUELDO_VENDEDOR);
  END IF;
END TR_B_IU_SUELDOVENDEDOR;


----OPERACION QUE DESPIERTA EL TRIGGER
INSERT INTO VENDEDOR (ID_VENDEDOR,CI_VENDEDOR,NOMBRE_VENDEDOR,APELLIDO_VENDEDOR,FECHA_NACIMIENTO,SEXO_VENDEDOR,CIUDAD_VENDEDOR,DIRECCION_VENDEDOR,CORREO_VENDEDOR,TELEFONO_VENDEDOR,SUELDO_VENDEDOR,FECHA_CONTRATO,TIPO_CONTRATO,FOTO_VENDEDOR)
VALUES (1,'13164534574','SLEIDER','PARRALES','3/09/1997','M','MANTA','SANTA CLARA CALLE 209 AV 45','SLEIDER@GMAIL.COM','0987568554',380,'6/09/2015','FIJO',NULL);