--1.
--Primer procedimiento almacenado para agregar un proveedor

create or replace PROCEDURE PA_INSERTAR_PROVEEDOR
   (ID_PROVEEDOR        IN INTEGER,
   NOMBRE_EMPRESA       IN VARCHAR2,
   PAIS_EMPRESA         IN VARCHAR2,
   CIUDAD_EMPRESA       IN VARCHAR2,
   DIRECCION_EMPRESA    IN VARCHAR2,
   NOMBRE_CONTACTO      IN VARCHAR2,
   APELLIDO_CONTACTO    IN VARCHAR2,
   TELEFONO_CONTACTO    IN VARCHAR2,
   CARGO_CONTACTO       IN VARCHAR2
)
AS
BEGIN

INSERT INTO PROVEEDOR VALUES (ID_PROVEEDOR,NOMBRE_EMPRESA,PAIS_EMPRESA,CIUDAD_EMPRESA,DIRECCION_EMPRESA,NOMBRE_CONTACTO,APELLIDO_CONTACTO,TELEFONO_CONTACTO,CARGO_CONTACTO);

END PA_INSERTAR_PROVEEDOR;


--1. BLOQUE ANONIMO PARA PROBAR EL PROCEDIMIENTO ALMACENADO

DECLARE
BEGIN 
 PA_INSERTAR_PROVEEDOR (1,'LA FABRIL S.A','ECUADOR','MANTA','FABRIL','JUAN ANDRES','MORALES ZAMBRANO','0998769490','EMPLEADO');
  END;
