
--3.
--Tercer procedimiento almacenado de agregar un producto 

create or replace PROCEDURE PA_INSERTAR_PRODUCTO
(
   ID_PRODUCTO          IN INTEGER,
   ID_PROVEEDOR         IN INTEGER,
   ID_CATEGORIA         IN INTEGER,
   NOMBRE_PRODUCTO      IN VARCHAR2,
   PRECIO_UNITARIO      IN FLOAT,
   UNIDADES_EXISTENTES  IN INTEGER,
   FECHA_VENCIMIENTO    IN DATE,
   DESCRIPCION          IN VARCHAR2,
   IMAGEN_PRODUCTO      IN BLOB
)
AS
BEGIN
INSERT INTO PRODUCTO VALUES (ID_PRODUCTO,ID_PROVEEDOR,ID_CATEGORIA,NOMBRE_PRODUCTO,PRECIO_UNITARIO,UNIDADES_EXISTENTES,FECHA_VENCIMIENTO,DESCRIPCION,IMAGEN_PRODUCTO);
END PA_INSERTAR_PRODUCTO;


----3. BLOQUE ANONIMO PARA PROBAR EL PROCEDIMIENTO ALMACENADO


DECLARE
BEGIN 
 PA_INSERTAR_PRODUCTO (1,1,1,'ACEITE LA FAVORITA',2,50,'5/04/2018','ACEITE LA FAVORITA DE 1 LITRO',null);
  END;