--4.
--Cuarto procedimiento almacenado de agregar un vendedor 

create or replace PROCEDURE PA_INSERTAR_VENDEDOR
(
   ID_VENDEDOR          IN INTEGER,
   CI_VENDEDOR          IN VARCHAR2,
   NOMBRE_VENDEDOR      IN VARCHAR2,
   APELLIDO_VENDEDOR    IN VARCHAR2,
   FECHA_NACIMIENTO     IN DATE,
   SEXO_VENDEDOR        IN VARCHAR2,
   CIUDAD_VENDEDOR      IN VARCHAR2,
   DIRECCION_VENDEDOR   IN VARCHAR2,
   CORREO_VENDEDOR      IN VARCHAR2,
   TELEFONO_VENDEDOR    IN VARCHAR2,
   SUELDO_VENDEDOR      FLOAT,
   FECHA_CONTRATO       IN DATE,
   TIPO_CONTRATO        IN VARCHAR2,
   FOTO_VENDEDOR        IN BLOB
)
AS
BEGIN
INSERT INTO VENDEDOR VALUES (ID_VENDEDOR,CI_VENDEDOR,NOMBRE_VENDEDOR,APELLIDO_VENDEDOR,FECHA_NACIMIENTO,SEXO_VENDEDOR,CIUDAD_VENDEDOR,DIRECCION_VENDEDOR,CORREO_VENDEDOR,TELEFONO_VENDEDOR,SUELDO_VENDEDOR,FECHA_CONTRATO,TIPO_CONTRATO,FOTO_VENDEDOR);
END PA_INSERTAR_VENDEDOR;

--4. BLOQUE ANONIMO PARA PROBAR EL PROCEDIMIENTO ALMACENADO

DECLARE
BEGIN 
 PA_INSERTAR_VENDEDOR (1,'13164534574','SLEIDER','PARRALES','3/09/1997','M','MANTA','SANTA CLARA CALLE 209 AV 45','SLEIDER@GMAIL.COM','0987568554',360,'6/09/2015','FIJO',NULL);
  END;