--5
--Quinto procedimiento almacenado de agregar un cliente

create or replace PROCEDURE PA_INSERTAR_CLIENTE
(
   ID_CLIENTE           INTEGER,
   CI_CLIENTE           VARCHAR2,
   NOMBRE_CLIENTE       VARCHAR2,
   APELLIDO_CLIENTE     VARCHAR2,
   TELEFONO_CLIENTE     VARCHAR2,
   CIUDAD_CLIENTE       VARCHAR2,
   DIRECCION_CLIENTE    VARCHAR2
)
AS
BEGIN
INSERT INTO CLIENTE VALUES (ID_CLIENTE,CI_CLIENTE,NOMBRE_CLIENTE,APELLIDO_CLIENTE,TELEFONO_CLIENTE,CIUDAD_CLIENTE,DIRECCION_CLIENTE);
END PA_INSERTAR_CLIENTE;


--5.. BLOQUE ANONIMO PARA PROBAR EL PROCEDIMIENTO ALMACENADO

DECLARE
BEGIN 
 PA_INSERTAR_CLIENTE (1,'13164598567','ANDRES','AGUILAR','0991693829','MANTA','BARRIO SAN PEDRO CALLE 31 AV 206');
  END;
