
--7.
--Séptimo procedimiento almacenado de agregar DETALLE_PEDIDO

create or replace PROCEDURE PA_INSERTAR_DETALLE_PEDIDO
(
   ID_PRODUCTO          IN INTEGER,
   ID_PEDIDO            IN INTEGER,
   CANTIDAD             IN INTEGER,
   PRECIO_SUBTOTAL      IN FLOAT,
   DESCUENTO            IN FLOAT,
   PRECIO_TOTAL         IN FLOAT
)
AS
BEGIN
INSERT INTO DETALLE_PEDIDO VALUES (ID_PRODUCTO,ID_PEDIDO,CANTIDAD,PRECIO_SUBTOTAL,DESCUENTO,PRECIO_TOTAL);
END PA_INSERTAR_DETALLE_PEDIDO;


--7. BLOQUE ANONIMO PARA PROBAR EL PROCEDIMIENTO ALMACENADO

DECLARE
BEGIN 
 PA_INSERTAR_DETALLE_PEDIDO (1,1,1,34,8,4);
  END;